# Generated by Django 3.2.25 on 2024-06-04 12:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('hashtags', '0001_initial'),  # Update this line
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='hashtags.Hashtag'),  # Update this line
        ),
    ]