# Generated by Django 3.2.25 on 2024-06-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
